---
version: '2.4'
services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    user: ${JELLYFIN_UID}:${JELLYFIN_GID}
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${JELLYFIN_DOCKER_BASE_DIR}/config:/config
      - ${JELLYFIN_DOCKER_BASE_DIR}/cache:/cache
      - ${JELLYFIN_MEDIA_BASE_DIR}/music:/media/music:ro
      - ${JELLYFIN_MEDIA_BASE_DIR}/movies:/media/movies:ro
      - ${JELLYFIN_MEDIA_BASE_DIR}/shows:/media/shows:ro
      - ${JELLYFIN_MEDIA_BASE_DIR}/podcasts:/media/podcasts:ro
      - ${JELLYFIN_MEDIA_BASE_DIR}/books:/media/books:ro
      - ${JELLYFIN_MEDIA_BASE_DIR}/audiobooks:/media/audiobooks:ro
        #    environment:
        #      - JELLYFIN_PublishedServerUrl=https://jellyfin.int.benvo.net
...
